{% set name = "rio-color" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 910b34fb32f15c1913a8172c87b3d81d148be84feed5e9a3a35417089791e7b4

build:
  number: 0
  entry_points:
    - color=rio_color.scripts.cli:color
    - atmos=rio_color.scripts.cli:atmos
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - click >=8.0
    - enum34  # [py<34]
    - python
    - rasterio >=1.4,<2.dev0
    - rio-mucho

test:
  imports:
    - rio_color
    - rio_color.scripts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mapbox/rio-color
  summary: Color correction plugin for rasterio
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsetiawan
