{% set name = "rio-color" %}
{% set version = "1.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8512ef2cd8bef8a8f891011044e1cc6eafd7200f858630bd441de1e7b7dac096

build:
  number: 4
  entry_points:
    - color=rio_color.scripts.cli:color
    - atmos=rio_color.scripts.cli:atmos
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - click >=4.0
    - enum34  # [py<34]
    - python
    - rasterio ~=1.0
    - rio-mucho

test:
  imports:
    - rio_color
    - rio_color.scripts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mapbox/rio-color
  summary: Color correction plugin for rasterio
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsetiawan
